[package]
name = "okay-loc"
version = "0.1.0"
authors = ["Barna RaÌtki <barna.ratki@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.1"
regex = "1.3.7"
anyhow = "1.0.31"
gitignore = "1.0.6"